version: "3.5"

networks:
    default:
        external:
            name: homelab

services:
    simulator:
        build:
            context: .
        image: loblab/resim
        hostname: resim
        container_name: resim
        stdin_open: true
        tty: true
        volumes:
            - ".:/script"
        command: [ "/script/simulator.py", "-D", "-c", "0.099", "-l", "100" ]

